-- MySQL Script generated by MySQL Workbench
-- qui 18 out 2018 23:41:31 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Motorista` (
  `idMotorista` INT NOT NULL,
  `NomeMotorista` VARCHAR(255) NULL,
  `CPF` INT NOT NULL,
  `Idade` INT NULL,
  `E-mail` VARCHAR(255) NULL,
  PRIMARY KEY (`idMotorista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TelefoneMotorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TelefoneMotorista` (
  `Telefone` INT NULL,
  `Motorista_idMotorista` INT NOT NULL,
  PRIMARY KEY (`Motorista_idMotorista`),
  CONSTRAINT `fk_TelefoneMotorista_Motorista`
    FOREIGN KEY (`Motorista_idMotorista`)
    REFERENCES `mydb`.`Motorista` (`idMotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EndereçoMotorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EndereçoMotorista` (
  `Motorista_idMotorista` INT NOT NULL,
  `Cidade` VARCHAR(255) NOT NULL,
  `Rua` VARCHAR(255) NOT NULL,
  `Bairo` VARCHAR(255) NOT NULL,
  `NumeroDaResidencia` INT NOT NULL,
  PRIMARY KEY (`Motorista_idMotorista`),
  CONSTRAINT `fk_EndereçoMotorista_Motorista1`
    FOREIGN KEY (`Motorista_idMotorista`)
    REFERENCES `mydb`.`Motorista` (`idMotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InfoCarro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InfoCarro` (
  `Motorista_idMotorista` INT NOT NULL,
  `ModeloDoCarro` VARCHAR(45) NOT NULL,
  `PlacaDoCarro` VARCHAR(8) NOT NULL,
  `Ano` DATE NOT NULL,
  `Cor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Motorista_idMotorista`),
  CONSTRAINT `fk_InfoCarro_Motorista1`
    FOREIGN KEY (`Motorista_idMotorista`)
    REFERENCES `mydb`.`Motorista` (`idMotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `CPF` INT NOT NULL,
  `Idade` INT NULL,
  `E-mail` VARCHAR(255) NULL,
  `NomeEmpresa` VARCHAR(255) NULL,
  `CartãoDeCredito` INT NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pgamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pgamento` (
  `Cliente_idCliente` INT NOT NULL,
  `Motorista_idMotorista` INT NOT NULL,
  `Valor` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Motorista_idMotorista`),
  INDEX `fk_Pgamento_Motorista1_idx` (`Motorista_idMotorista` ASC) VISIBLE,
  CONSTRAINT `fk_Pgamento_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pgamento_Motorista1`
    FOREIGN KEY (`Motorista_idMotorista`)
    REFERENCES `mydb`.`Motorista` (`idMotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TelefoneCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TelefoneCliente` (
  `Cliente_idCliente` INT NOT NULL,
  `Telefone` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`),
  CONSTRAINT `fk_TelefoneCliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EndereçoCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EndereçoCliente` (
  `Cliente_idCliente` INT NOT NULL,
  `Cidade` VARCHAR(255) NOT NULL,
  `Rua` VARCHAR(255) NOT NULL,
  `Bairo` VARCHAR(255) NOT NULL,
  `NumeroDaResidencia` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`),
  CONSTRAINT `fk_EndereçoCliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Viagem` (
  `Motorista_idMotorista` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Emdereço` VARCHAR(255) NOT NULL,
  `TipoDeCarga` VARCHAR(255) NULL,
  `IdViagem` INT NOT NULL,
  PRIMARY KEY (`Motorista_idMotorista`, `Cliente_idCliente`, `IdViagem`),
  INDEX `fk_Motorista_has_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Motorista_has_Cliente_Motorista1_idx` (`Motorista_idMotorista` ASC) VISIBLE,
  CONSTRAINT `fk_Motorista_has_Cliente_Motorista1`
    FOREIGN KEY (`Motorista_idMotorista`)
    REFERENCES `mydb`.`Motorista` (`idMotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Motorista_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historico` (
  `Viagem_IdViagem` INT NOT NULL,
  `Cliente` VARCHAR(255) NOT NULL,
  `Motorista` VARCHAR(255) NOT NULL,
  `Data` DATE NOT NULL,
  `TempoDeViagem` TIME NOT NULL,
  `TipoDeCarga` VARCHAR(45) NOT NULL,
  `ValorPago` INT NOT NULL,
  PRIMARY KEY (`Viagem_IdViagem`),
  CONSTRAINT `fk_Historico_Viagem1`
    FOREIGN KEY (`Viagem_IdViagem`)
    REFERENCES `mydb`.`Viagem` (`IdViagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
